apiVersion: apps/v1
kind: Deployment
metadata:
  name: vshop-product-api
  namespace: vshop
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/instance: vshop-product-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vshop-product
        app.kubernetes.io/component: backend
        app.kubernetes.io/instance: vshop-product-api
    spec:
      containers:
      - name: vshop-product-api
        image: vshopproduct:latest
        imagePullPolicy: Never
        env:
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: sqlserver-secret
              key: DefaultConnection
        - name: UrlUI__VShopWebUI
          value: "http://192.168.49.2:32001"
        resources:
          limits:
            memory: "128Mi"
            cpu: "128m"
        ports:
        - containerPort: 8080
