apiVersion: apps/v1
kind: Deployment
metadata:
  name: vshop-web-ui
  namespace: vshop
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: vshop-web-ui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vshop-web
        app.kubernetes.io/component: frontend
        app.kubernetes.io/instance: vshop-web-ui
    spec:
      containers:
      - name: vshop-web-ui
        image: vshopweb:latest
        imagePullPolicy: Never
        env:
        - name: ServiceUri__ProductApi
          valueFrom:
            configMapKeyRef:
              name: vshop-web-ui-config 
              key: VShopProductApi
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 8080
