name: Docker CI

on:
  push:
    branches:
      - main

jobs: 
  build-and-push:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKERHUB: ${{ vars.DOCKERHUB}}
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      # Product API
      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: ./VShop.ProductApi
          file: ./VShop.ProductApi/Dockerfile
          push: true
          tags: ${{ env.DOCKERHUB }}/vshopproduct:latest

      # UI
      - name: Build and push UI image
        uses: docker/build-push-action@v5
        with:
          context: ./VShop.Web
          file: ./VShop.Web/Dockerfile
          push: true
          tags: ${{ env.DOCKERHUB }}/vshopweb:latest
        
      - name: Create dir
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.EC2_HOST }}
          username: ubuntu
          key: ${{ env.EC2_SSH_KEY }}
          script: |
            mkdir -p /home/ubuntu/deploy

      - name: Copy manifests to EC2
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ env.EC2_HOST }}
          username: ubuntu
          key: ${{ env.EC2_SSH_KEY }}
          port: 22
          source: "kubernetes-deployment/*"
          target: "/home/ubuntu/deploy/"


      
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.EC2_HOST }}
          username: ubuntu
          key: ${{ env.EC2_SSH_KEY }}
          script: |
            kubectl get namespace vshop || kubectl create namespace vshop
            kubectl apply -f /home/ubuntu/deploy/ -n vshop
            kubectl rollout restart deployment vshop-product-api -n vshop
            kubectl rollout restart deployment vshop-web-ui -n vshop